In [1]:
import numpy as np
import pandas as pd


In [15]:
# creating a dataFrame with duplicate rows
df = pd.DataFrame({"Name":["Jack", "Jill", "John", "Jack"], "Rank":[1,21,3,1], "Marks":[99,56,97,99]})
df


Marks  Name  Rank
0     99  Jack     1
1     56  Jill    21
2     97  John     3
3     99  Jack     1

In [17]:
# dropiing the duplicate rows but keeping the first row that has a duplicate below in the dataset
df.drop_duplicates(keep='first')

Marks  Name  Rank
0     99  Jack     1
1     56  Jill    21
2     97  John     3

In [19]:
# drop all the duplicate rows, so not keep any duplicate rows
df.drop_duplicates(keep=False)

Marks  Name  Rank
1     56  Jill    21
2     97  John     3

In [20]:
# since inplace is set to false by default, the dataframe remains as it is
df

Marks  Name  Rank
0     99  Jack     1
1     56  Jill    21
2     97  John     3
3     99  Jack     1

In [22]:
# changing the dataset by settig inplace  to true
df.drop_duplicates(keep='first', inplace=True)
df

Marks  Name  Rank
0     99  Jack     1
1     56  Jill    21
2     97  John     3

In [66]:
# reading titanic dataset
data_set = pd.read_csv("train.csv")

In [67]:
data_set.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [68]:
# drooping irrelevant columns in the dataset and modifying the dataset
data_set.drop(['Name', 'Ticket'], inplace=True, axis=1)
data_set.head(3)


PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin  \
0            1         0       3    male  22.0      1      0   7.2500   NaN   
1            2         1       1  female  38.0      1      0  71.2833   C85   
2            3         1       3  female  26.0      0      0   7.9250   NaN   

  Embarked  
0        S  
1        C  
2        S

In [69]:
data_set.tail()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch   Fare Cabin  \
886          887         0       2    male  27.0      0      0  13.00   NaN   
887          888         1       1  female  19.0      0      0  30.00   B42   
888          889         0       3  female   NaN      1      2  23.45   NaN   
889          890         1       1    male  26.0      0      0  30.00  C148   
890          891         0       3    male  32.0      0      0   7.75   NaN   

    Embarked  
886        S  
887        S  
888        S  
889        C  
890        Q

## Handling Missing Values

In [131]:
data_set.dropna(inplace = True)
data_set.head(3)


PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin  \
1            2         1       1  female  38.0      1      0  71.2833   C85   
3            4         1       1  female  35.0      1      0  53.1000  C123   
6            7         0       1    male  54.0      0      0  51.8625   E46   

  Embarked  
1        C  
3        S  
6        S

In [132]:
data_1 = pd.DataFrame({"City":["Mumbai", "New York", "London", "San Francisco"], "Ratings":[np.nan,2,np.nan,1], "Average Age":[np.nan,70,85,np.nan]})
data_1


Average Age           City  Ratings
0          NaN         Mumbai      NaN
1         70.0       New York      2.0
2         85.0         London      NaN
3          NaN  San Francisco      1.0

In [134]:
data_1.dropna(thresh=2)


Average Age           City  Ratings
1         70.0       New York      2.0
2         85.0         London      NaN
3          NaN  San Francisco      1.0

In [135]:
data_1

Average Age           City  Ratings
0          NaN         Mumbai      NaN
1         70.0       New York      2.0
2         85.0         London      NaN
3          NaN  San Francisco      1.0

In [141]:
#filling Nan value in Rating  column with mean of the Ratings column
data_1['Ratings'].fillna(data_1['Ratings'].mean(), inplace = True)
data_1

Average Age           City  Ratings
0          NaN         Mumbai      1.5
1         70.0       New York      2.0
2         85.0         London      1.5
3          NaN  San Francisco      1.0

In [142]:
#filling Nan value in Average Age  column with median of the Average Age column
data_1['Average Age'].fillna(data_1['Average Age'].median(), inplace = True)
data_1

Average Age           City  Ratings
0         77.5         Mumbai      1.5
1         70.0       New York      2.0
2         85.0         London      1.5
3         77.5  San Francisco      1.0

In [145]:
from sklearn.preprocessing import Imputer
countryData = pd.DataFrame({"Country":["France","Spain", "Germany", "USA"], "Age":[np.nan,45,np.nan,32], "Salary":[np.nan,90000,np.nan,75000]})
countryData


Age  Country   Salary
0   NaN   France      NaN
1  45.0    Spain  90000.0
2   NaN  Germany      NaN
3  32.0      USA  75000.0

In [146]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)


In [150]:
imp.fit(countryData.iloc[:,[0,2]])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [151]:
countryData.iloc[:,[0,2]]=imp.transform(countryData.iloc[:,[0,2]])

In [152]:
countryData

Age  Country   Salary
0  38.5   France  82500.0
1  45.0    Spain  90000.0
2  38.5  Germany  82500.0
3  32.0      USA  75000.0

In [153]:
countryData = pd.DataFrame({"Country":["France","Spain", "Germany", "USA"], "Age":[np.nan,45,np.nan,32], "Salary":[np.nan,90000,np.nan,75000]})
countryData

Age  Country   Salary
0   NaN   France      NaN
1  45.0    Spain  90000.0
2   NaN  Germany      NaN
3  32.0      USA  75000.0

In [158]:
countryData.replace({'Age':np.NAN},40 )

Age  Country   Salary
0  40.0   France      NaN
1  45.0    Spain  90000.0
2  40.0  Germany      NaN
3  32.0      USA  75000.0

In [162]:
# filtering outliers
import numpy as np
def detect_outlier(data_1):
    threshold=3
    mean_1 = np.mean(data_1)
    std_1 =np.std(data_1)
    z_score = [(y - mean_1)/std_1 for y in data_1]
    val= np.where(np.abs(z_score) > threshold)


In [168]:
countryData = pd.DataFrame({"Country":["France","Spain", "Germany", "USA"], "Age":[500,45,23,32], "Salary":[1000,90000,60000,75000]})
countryData

Age  Country  Salary
0  500   France    1000
1   45    Spain   90000
2   23  Germany   60000
3   32      USA   75000

In [171]:
 a= []
 a= detect_outlier(countryData['Age'])

In [172]:
a


(array([], dtype=int64),)

In [173]:
a = np.arange(5,10)
a

array([5, 6, 7, 8, 9])

In [174]:
np.where(a>8)

(array([4], dtype=int64),)

In [176]:
b=a[np.where(a>8)]
b

array([9])

In [183]:
import pandas as pd
import numpy as np

def find_outliers(data_1):
    threshold=3
    outliers=[]
    mean_1 = np.mean(data_1)
    std_1 =np.std(data_1)
        
    for y in data_1:
        z_score= (y - mean_1)/std_1 
        
        if np.abs(z_score) > threshold:
            outliers.append(y)
    return outliers

In [184]:
# reading titanic dataset
data_set = pd.read_csv("train.csv")

In [185]:
a = []
a = find_outliers(data_set['Age'])
print(a)

[80.0, 74.0]
